global:
  scrape_interval: 2s  # Adjust as needed

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: 
        - localhost:8000 # Adjust the IP address and port of your Flask application

